"""Seed data for the fake airline.

All times are local to their airport and carry an explicit UTC offset, so the
backend can compare them across timezones without guessing. The demo day is
2026-08-17.

Kept separate from main.py so the backend can be reset to a known state
(POST /admin/reset) after rebookings have mutated it.
"""

# status: ON_TIME | DELAYED | CANCELLED
# seats_available is the number of seats an agent may rebook into.
FLIGHTS = [
    # --- IAD -> DEN (the canonical disruption) ---
    {
        "flight_no": "UA482",
        "origin": "IAD",
        "dest": "DEN",
        "scheduled_departure": "2026-08-17T18:05:00-04:00",
        "scheduled_arrival": "2026-08-17T20:10:00-06:00",
        "status": "CANCELLED",
        "reason": "crew availability",
        "gate": "C17",
        "seats_available": 0,
    },
    {
        "flight_no": "UA905",
        "origin": "IAD",
        "dest": "DEN",
        "scheduled_departure": "2026-08-17T19:30:00-04:00",
        "scheduled_arrival": "2026-08-17T21:35:00-06:00",
        "status": "ON_TIME",
        "reason": None,
        "gate": "C11",
        "seats_available": 0,  # sold out
    },
    {
        "flight_no": "UA1220",
        "origin": "IAD",
        "dest": "DEN",
        "scheduled_departure": "2026-08-17T20:15:00-04:00",
        "scheduled_arrival": "2026-08-17T22:20:00-06:00",
        "status": "DELAYED",
        "reason": "late inbound aircraft",
        "gate": "C6",
        "seats_available": 2,
    },
    {
        "flight_no": "UA118",
        "origin": "IAD",
        "dest": "DEN",
        "scheduled_departure": "2026-08-17T21:40:00-04:00",
        "scheduled_arrival": "2026-08-17T23:45:00-06:00",
        "status": "ON_TIME",
        "reason": None,
        "gate": "C22",
        "seats_available": 6,
    },
    {
        "flight_no": "UA77",
        "origin": "IAD",
        "dest": "DEN",
        "scheduled_departure": "2026-08-17T22:55:00-04:00",
        "scheduled_arrival": "2026-08-18T01:00:00-06:00",
        "status": "ON_TIME",
        "reason": None,
        "gate": "C19",
        "seats_available": 14,
    },
    # --- DCA -> ATL ---
    {
        "flight_no": "DL201",
        "origin": "DCA",
        "dest": "ATL",
        "scheduled_departure": "2026-08-17T19:15:00-04:00",
        "scheduled_arrival": "2026-08-17T21:20:00-04:00",
        "status": "DELAYED",
        "reason": "late inbound aircraft",
        "gate": "B4",
        "seats_available": 9,
    },
    {
        "flight_no": "DL388",
        "origin": "DCA",
        "dest": "ATL",
        "scheduled_departure": "2026-08-17T20:40:00-04:00",
        "scheduled_arrival": "2026-08-17T22:45:00-04:00",
        "status": "ON_TIME",
        "reason": None,
        "gate": "B9",
        "seats_available": 0,  # sold out
    },
    {
        "flight_no": "DL512",
        "origin": "DCA",
        "dest": "ATL",
        "scheduled_departure": "2026-08-17T21:50:00-04:00",
        "scheduled_arrival": "2026-08-17T23:55:00-04:00",
        "status": "ON_TIME",
        "reason": None,
        "gate": "B12",
        "seats_available": 5,
    },
    # --- JFK -> LAX ---
    {
        "flight_no": "AA330",
        "origin": "JFK",
        "dest": "LAX",
        "scheduled_departure": "2026-08-17T17:20:00-04:00",
        "scheduled_arrival": "2026-08-17T20:35:00-07:00",
        "status": "CANCELLED",
        "reason": "severe weather at JFK",
        "gate": "8",
        "seats_available": 0,
    },
    {
        "flight_no": "AA1512",
        "origin": "JFK",
        "dest": "LAX",
        "scheduled_departure": "2026-08-17T19:05:00-04:00",
        "scheduled_arrival": "2026-08-17T22:20:00-07:00",
        "status": "ON_TIME",
        "reason": None,
        "gate": "12",
        "seats_available": 3,
    },
    {
        "flight_no": "AA88",
        "origin": "JFK",
        "dest": "LAX",
        "scheduled_departure": "2026-08-17T20:30:00-04:00",
        "scheduled_arrival": "2026-08-17T23:45:00-07:00",
        "status": "ON_TIME",
        "reason": None,
        "gate": "10",
        "seats_available": 0,  # sold out
    },
    {
        "flight_no": "AA210",
        "origin": "JFK",
        "dest": "LAX",
        "scheduled_departure": "2026-08-17T22:00:00-04:00",
        "scheduled_arrival": "2026-08-18T01:15:00-07:00",
        "status": "DELAYED",
        "reason": "air traffic control flow program",
        "gate": "14",
        "seats_available": 11,
    },
    # --- ORD -> SFO ---
    {
        "flight_no": "UA640",
        "origin": "ORD",
        "dest": "SFO",
        "scheduled_departure": "2026-08-17T18:45:00-05:00",
        "scheduled_arrival": "2026-08-17T21:20:00-07:00",
        "status": "ON_TIME",
        "reason": None,
        "gate": "B18",
        "seats_available": 7,
    },
    {
        "flight_no": "UA1284",
        "origin": "ORD",
        "dest": "SFO",
        "scheduled_departure": "2026-08-17T21:10:00-05:00",
        "scheduled_arrival": "2026-08-17T23:45:00-07:00",
        "status": "ON_TIME",
        "reason": None,
        "gate": "C8",
        "seats_available": 1,
    },
    # --- LHR -> JFK (transatlantic; EU261 territory in Phase 3) ---
    {
        "flight_no": "BA117",
        "origin": "LHR",
        "dest": "JFK",
        "scheduled_departure": "2026-08-17T14:30:00+01:00",
        "scheduled_arrival": "2026-08-17T17:30:00-04:00",
        "status": "CANCELLED",
        "reason": "technical fault",
        "gate": "A10",
        "seats_available": 0,
    },
    {
        "flight_no": "BA179",
        "origin": "LHR",
        "dest": "JFK",
        "scheduled_departure": "2026-08-17T18:20:00+01:00",
        "scheduled_arrival": "2026-08-17T21:20:00-04:00",
        "status": "ON_TIME",
        "reason": None,
        "gate": "A14",
        "seats_available": 4,
    },
]

# fare_class drives rebooking/refund rules once policy RAG lands in Phase 3.
BOOKINGS = [
    {
        "booking_ref": "K7QM2P",
        "passenger": "Ibrahim Khan",
        "last_name": "Khan",
        "flight_no": "UA482",
        "fare_class": "ECONOMY_BASIC",
        "seat": "14C",
        "status": "CONFIRMED",
    },
    {
        "booking_ref": "R4ZT9L",
        "passenger": "Maria Alvarez",
        "last_name": "Alvarez",
        "flight_no": "UA482",
        "fare_class": "ECONOMY_FLEX",
        "seat": "8A",
        "status": "CONFIRMED",
    },
    {
        "booking_ref": "H2WD5X",
        "passenger": "James Okafor",
        "last_name": "Okafor",
        "flight_no": "DL201",
        "fare_class": "MAIN_CABIN",
        "seat": "22F",
        "status": "CONFIRMED",
    },
    {
        "booking_ref": "G3JF7Q",
        "passenger": "Daniel Weber",
        "last_name": "Weber",
        "flight_no": "DL201",
        "fare_class": "BASIC_ECONOMY",
        "seat": "30E",
        "status": "CONFIRMED",
    },
    {
        "booking_ref": "P9NK3B",
        "passenger": "Wei Chen",
        "last_name": "Chen",
        "flight_no": "AA330",
        "fare_class": "BUSINESS",
        "seat": "3B",
        "status": "CONFIRMED",
    },
    {
        "booking_ref": "T5VC8M",
        "passenger": "Sofia Rossi",
        "last_name": "Rossi",
        "flight_no": "BA117",
        "fare_class": "ECONOMY_FLEX",
        "seat": "31D",
        "status": "CONFIRMED",
    },
    {
        "booking_ref": "L8XR6D",
        "passenger": "Priya Nair",
        "last_name": "Nair",
        "flight_no": "UA640",
        "fare_class": "PREMIUM_ECONOMY",
        "seat": "11A",
        "status": "CONFIRMED",
    },
    {
        "booking_ref": "N6BS4Y",
        "passenger": "Amara Diallo",
        "last_name": "Diallo",
        "flight_no": "UA118",
        "fare_class": "MAIN_CABIN",
        "seat": "19C",
        "status": "CONFIRMED",
    },
]
